/*
 * This source file was generated by the Gradle 'init' task
 */
package com.T4C30.Backtrack;

import com.T4C30.Backtrack.Control.SQLite;
import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application{
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage ventana) throws Exception {
        SQLite.comprobacion();
        Parent raiz = FXMLLoader.load(getClass().getResource("/com/T4C30/Recurso/Menu.fxml"));
        Scene escena = new Scene(raiz);
        ventana.setScene(escena);
        ventana.show();
    }

    @FXML
    public void editor() throws IOException{
        Stage ventana = new Stage();
        Parent raiz = FXMLLoader.load(getClass().getResource("/com/T4C30/Recurso/Editor.fxml"));
        Scene escena = new Scene(raiz);
        ventana.setScene(escena);
        ventana.show();
    }

}